### ISSUE TITLE
Wrong placeholder in enable-rpi-hid

### ISSUE THREAD

**Issue by lrabe** [mtlynch/tinypilot#119]
In enable-usb-hid, the following sed substitution is supposed to replace the `{{ key_mime_pi_initialize_hid_script_path }}` placeholder:

https://github.com/mtlynch/tinypilot/blob/8b41bb08f6b0312f8e500f562a35bbe1621183df/enable-usb-hid#L30-L31

In the corresponding file the placeholder is called `{{ tinypilot_initialize_hid_script_path }}` though:

https://github.com/mtlynch/ansible-role-tinypilot/blob/21514df253b1fa9e6e6d390ef907f5544b2135eb/templates/usb-gadget.systemd.j2#L8

Looks like the enable-usb-hid script uses an identifier from the deprecated key-mime-pi project.

**Comment by mtlynch** [comment]
Oh, good catch. That one confused me for a few minutes because I couldn't figure out how the incorrect variable name wasn't creating problems, but I realized that file is actually dead code. We now create that file with the Ansible role:

https://github.com/mtlynch/ansible-role-tinypilot/blob/21514df253b1fa9e6e6d390ef907f5544b2135eb/tasks/install_usb_gadget.yml#L22-L28
