### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by danmed** [mtlynch/tinypilot#169]
I've noticed there has been some mouse support added.. but i'm not sure to what extent.. is there a changelog somewhere or an update to something that i'm missing that details these type of changes?

**Comment by mtlynch** [comment]
Every time I cut a release, I publish a changelog:

https://github.com/mtlynch/tinypilot/releases

I've added mouse support, but I'm the only one who's tested it, so I'd love some feedback from others before I cut the official release.

To be clear, cutting the releases is just recordkeeping. The update script pulls down the latest `master` branch unless you specify otherwise.
