### ISSUE TITLE
Power cycling a system with GPIO pins

### ISSUE THREAD

**Issue by rubyrose96** [mtlynch/tinypilot#410]
Started playing with tintpilot the other day and loving it so far. 
Having the ability to emulate the power button would be useful, seeing as the pi has GPIO headers it'd be easy to hook it up to a [relay module](https://thepihut.com/products/gravity-relay-module-v3-1) to be able to turn on or force shudown a system.
How does this sound?

**Comment by mtlynch** [comment]
Thanks for reaching out!

I'm definitely interested in power management, but I want to keep the solution something that an average IT pro could set up. All the relay module options I've seen involve soldering or setting up breadboards and plugging directly into the motherboard, and that's very different from the rest of the way TinyPilot works.

I'm looking into a packaged offering based on [this device](https://dlidirect.com/products/iot-power-relay), but I need to do some work there because out of the box, that power strip still requires jumper wire.

**Comment by rubyrose96** [comment]
That's fair enough, I see how it'd be the easier option for an end used to implement. 
Do you have any pointers as to how something like my idea could be implemented? I'm a still new to python so my knowledge is a bit lacking, as this is open source I'd like to play around with it a bit.

**Comment by mtlynch** [comment]
You might want to check out this project, as it's similar but it implemented power management:

https://github.com/Fmstrat/diy-ipmi
