### ISSUE TITLE
Raspberry Pi 4 requirement

### ISSUE THREAD

**Issue by ybizeul** [mtlynch/tinypilot#77]
Did anybody try to run this on a Pi 3 instead ? Does it makes such a difference ?

**Comment by ybizeul** [comment]
Closing this issue, USB-Gadget missing from Pi3 is probably the reason.

**Comment by m0khalifa** [comment]
Can confirm this, I've set up tinypilot on an old Raspberry PI 3B and the whole system works apart from the keyboard input due to lack of OTG supporting ports. It's a little more laggy at times but shows everything and is useful for changing BIOS settings with a laptop (to show the tinypilot interface) and a keyboard plugged directly into the needed server.
