### ISSUE TITLE
Pi Zero W

### ISSUE THREAD

**Issue by peterberbec** [mtlynch/tinypilot#93]
The lower power requirements, smaller size, and lower heat of the Pi0 allow for an interesting possibility. The 0 could be totally powered through the OTG cable and with a otg adapter, the hdmi capture card could still be attached.

I'm picking up a P and a OTG adapter. I will report back.

**Comment by peterberbec** [comment]
It's here and I'm doing the install. Updates later. Pi 0 is slow, but that shouldn't matter since the overhead is minimal, right?

![20200729_205047_HDR](https://user-images.githubusercontent.com/17226353/88868104-4727f500-d1dd-11ea-933d-82a6cfdb7b6e.jpg)

**Comment by peterberbec** [comment]
Works

![20200730_010738_HDR](https://user-images.githubusercontent.com/17226353/88882983-207bb580-d201-11ea-9068-3145b96daa26.jpg)

**Comment by mtlynch** [comment]
Nice! Thanks for testing that, @peterberbec!

**Comment by rvdwegen** [comment]
@peterberbec what was the video performance like?

**Comment by peterberbec** [comment]
It was definately NOT under 200ms of lag, but usable.

I'm testing out a FriendlyElec NanoPi Meo mext

**Comment by mtlynch** [comment]
@peterberbec would you be able to share the name/link of the USB cable you're using with the Pi?

**Comment by peterberbec** [comment]
The microUSB to regular USB and charging port cable?

That's a microUSB OTG/charge cable.

https://www.amazon.com/dp/B07FY9Z9GD

**Comment by rvdwegen** [comment]
Hey, did you have to make any changes or was it plug and play on the Pi zero?

**Comment by peterberbec** [comment]
Plug, curl | bash, play

Peter Berbec
(917) 213-2594

**Comment by rvdwegen** [comment]
And the keyboard works too?

**Comment by somik123** [comment]
> And the keyboard works too?

Doubt it. Pi zero has only 1 USB that supports data (other one is power only, no data). So it can either behave as host (for the HDMI adapter) or as OTG (for keyboard input). Since he is using the only data port for HDMI to usb adapter, no keyboard input is available.

![Pi-Zero-Features-Graphic-Small](https://user-images.githubusercontent.com/7911288/89706999-26aa2880-d99d-11ea-8734-37d5a2597ba1.jpg)

**Comment by peterberbec** [comment]
I could have connected a hub to the otg, or a Bluetooth keyboard, but I
didn't. I can test such a setup if their is interest. I was doing it as a
test of the Zero platform's viability, and the speed makes it not useful to
me.

**Comment by somik123** [comment]
@peterberbec 
> I could have connected a hub to the otg, or a Bluetooth keyboard, but I didn't. I can test such a setup if their is interest. I was doing it as a test of the Zero platform's viability, and the speed makes it not useful to me.


I did connect it to a usb hub. Only the video capture works. You need to connect it directly to PC without any hub to get the keyboard input to work, but then video wont work. So you have to choose between the two. You dont have 2 usb controllers to make one act as host and the other device, so both video and keyboard wont work at the same time on zero for now.

**Comment by peterberbec** [comment]
Ah. My mistake. I thought you meant a keyboard to the Pi, not the otg
keyboard

**Comment by somik123** [comment]
> Ah. My mistake. I thought you meant a keyboard to the Pi, not the otg keyboard

Ya, i meant the device mode where the Pi sends keyboard input to the PC.

**Comment by mtlynch** [comment]
One idea for the Pi Zero would be to use the CSI bridge to capture HDMI, like this one:

https://www.ebay.com/itm/For-Raspberry-Pi-HDMI-To-CSI-2-C779-Bridge-Adapter-Interface-Module-1080p-25fps/203009279885

That capture card works with TinyPilot, though the Ansible role requires a few tweaks to handle the HDMI to CSI-2 bridge instead of the HDMI dongle.

**Comment by peterberbec** [comment]
Purchased. I will report back

**Comment by peterberbec** [comment]
> 
> 
> One idea for the Pi Zero would be to use the CSI bridge to capture HDMI, like this one:
> 
> https://www.ebay.com/itm/For-Raspberry-Pi-HDMI-To-CSI-2-C779-Bridge-Adapter-Interface-Module-1080p-25fps/203009279885
> 
> That capture card works with TinyPilot, though the Ansible role requires a few tweaks to handle the HDMI to CSI-2 bridge instead of the HDMI dongle.

I purchased that exact adapter, and it works. Keyboard input does not seem to be functioning. What steps should I go through to troubleshoot g_hid?

**Comment by peterberbec** [comment]
> 
> 
> > One idea for the Pi Zero would be to use the CSI bridge to capture HDMI, like this one:
> > https://www.ebay.com/itm/For-Raspberry-Pi-HDMI-To-CSI-2-C779-Bridge-Adapter-Interface-Module-1080p-25fps/203009279885
> > That capture card works with TinyPilot, though the Ansible role requires a few tweaks to handle the HDMI to CSI-2 bridge instead of the HDMI dongle.
> 
> I purchased that exact adapter, and it works. Keyboard input does not seem to be functioning. What steps should I go through to troubleshoot g_hid?

Step 1: Use a usb cable that supports data, not just charging.

It's working!

**Comment by rvdwegen** [comment]
Excellent news!

This could make for a fairly compact package if one were to take a Lusya bridge from China (same screw holes as pi zero) and one of those cheapo USB stick conversion PCB's.

https://ae01.alicdn.com/kf/Hc7195b14d18d425f8a7b76b48621d9a66.jpg
https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/87/A8/f81af760-9f26-4101-b1f9-0e25273cd1fa.jpg

**Comment by somik123** [comment]
![IMG_20200903_204506](https://user-images.githubusercontent.com/7911288/92116585-9c7fa380-ee26-11ea-950c-0f771cf110b1.jpg)

![IMG_20200903_204454](https://user-images.githubusercontent.com/7911288/92116603-a0abc100-ee26-11ea-8db4-a855464af57c.jpg)

**Comment by somik123** [comment]
From top:
HDMI to CSI bridge, 
Raspberry Pi Zero W, 
1000mAh battery module.

**Comment by espoelstra** [comment]
@somik123 that is awesome!!! I had a similar idea but hadn't thought to put a battery in there to allow the Pi0 to still function (probably for HOURS) through host reboots or brief power outages.

I think I have a CSI bridge from that same company but with a larger footprint closer to the Pi0 size. Did you have to do anything special to get it recognized by TinyPilot?

**Comment by somik123** [comment]
> @somik123 that is awesome!!! I had a similar idea but hadn't thought to put a battery in there to allow the Pi0 to still function (probably for HOURS) through host reboots or brief power outages.
> 
> I think I have a CSI bridge from that same company but with a larger footprint closer to the Pi0 size. Did you have to do anything special to get it recognized by TinyPilot?

Yes, there was a bit of configuration change involved. I can't find that thread now though. You need to change the startup script for the video capture software to ensure it gets the data from this csi bridge instead of looking for a USB device.

**Comment by mtlynch** [comment]
I'm working on handling the HDMI to CSI chip configuration natively in the TinyPilot installer. For now, you can do this:

```bash
export TINYPILOT_INSTALL_VARS="ustreamer_encoder=omx ustreamer_capture_device=tc358743 ustreamer_workers=3 ustreamer_drop_same_frames=30 ustreamer_use_dv_timings=yes ustreamer_format=uyvy"
curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/mtlynch/tinypilot/master/quick-install | \
    bash - && \
  sudo reboot
```

I'm working on that this week, though, so expect a better solution within days.

**Comment by swbullis** [comment]
### The right way
I, unfortunately, didn't see this issue yesterday when I was testing things out, however, I want to call out @somik123 solution above as the way forward. 

Having a dedicated power supply (battery) solves the problem of the pi resetting during reboots.  And installing a ZeroStem ( I bought mine here https://www.adafruit.com/product/3945) that you can solder onto the board makes for a very compact solution.

And of course, to get the video into the raspberry pi you will need something like this https://www.ebay.com/itm/For-Raspberry-Pi-HDMI-To-CSI-2-C779-Bridge-Adapter-Interface-Module-1080p-25fps/203009279885 

this is because the Pi Zero only has one USB port so it can send data on that port  (gadget mode) or receive data on that port (regular mode) all of this is said higher up in other comment but I am including it here for thoroughness.

### The Easy way
Ultimately what I ended up doing was ordering a Pi 4

### The I can't wait I need it now way

However as stop gap until the correct parts arrived. I took the following actions which might be useful if you happen to have 2 Pi Zero W's available to you.

Install TinyPilot on Both Pi's and setup 1 to Receive Video using the HDMI to USB Adapter (This is just plugging in the adapter)
You should be able to test that it's working by navigating to the IP address for that device.

Setup the other as normal this one will be used to emulate the keyboard and mouse.  (No video adapter connected)

Plug both into your target computer and navigate to the IP address of Pi 2 (Keyboard and mouse one).  Go into your developer tools and change the image address to point to the IP address of the other Tiny Pilot.

It should look something like this

```
<div class="screen-wrapper" cursor="crosshair">
    <input id="mobile-keyboard-input" autocapitalize="off" type="text">
    <img id="remote-screen-img" src="http://192.168.1.111/stream?advance_headers=1">
  </div>
```

Hope this helps someone else!

**Comment by peterberbec** [comment]
Thinking about this now, I wonder why a Bluetooth keyboard & mouse didn't
occur to me. Csi for hdmi input, usb for HID to "main" computer, the pi's
Micro (?) hdmi for video, and Bluetooth keyboard/mouse.

**Comment by mtlynch** [comment]
I improved handling HDMI to CSI capture devices. The best way to configure for it is now this:

```bash
export TINYPILOT_INSTALL_VARS="ustreamer_capture_device=tc358743"
curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/mtlynch/tinypilot/master/quick-install | \
    bash - && \
  sudo reboot
```

I did some experimenting today with the Pi Zero:

https://twitter.com/tinypilotkvm/status/1329881175847002113

It seems way too slow to be a feasible platform for TinyPilot. Are others just dialing down the resolution to 640x480 or something tiny?

**Comment by tristan-k** [comment]
Did anyone try to use the bluetooth of rpi zero w as an iput method for tinypilot? I'm still trying to figure out a way for input on the zero w without buying a csi bridge.
