### ISSUE TITLE
Restrict CORS origins for socket.io connections

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#99]
In #98, I removed strict checking for CORS requests. My reasoning is that it's not providing meaningful protection at the moment, but it's creating significant usability issues (see #97).

CORS origin checking currently does not much protection because:

1. The user base of TinyPilot is so small that CSRF attacks are highly unlikely.
1. Even with CORS origin checking, third-party origins can still send requests to the `/socket.io` route from the user's browser. CORS enforcement prevents them from reading responses, but there's nothing useful in the responses anyway.

We should revisit this decision in the future to ensure that we're not sacrificing real protection by dropping origin checking, even if (1) is no longer true.

**Comment by Bramzor** [comment]
True, I think CORS has almost no benefit especially since there is no authentication and traffic is not going over HTTPS. So I'm more worried about passwords that are  possibly going over an unencrypted connection.

If HTTPS would be added (not easy to do and takes additional resources), activating CORS would be a no brainer as using the correct hostname becomes a requirement anyway.

**Comment by mtlynch** [comment]
Reopening as the previous fix caused a regression. When users accessed TinyPilot from a different URL, it broke the websocket connection.

Need to investigate more how to make SocketIO cooperate.

**Comment by mtlynch** [comment]
From tinkering some more, it seems to be related to nginx. Connecting directly to TinyPilot without nginx works as expected.

I need to review the nginx config here:

https://flask-socketio.readthedocs.io/en/latest/#using-nginx-as-a-websocket-reverse-proxy
